server:
  port: 8090
spring:
  application:
    name: fleet-service
  mongodb:
    uri: ${ MONGO_URI }

  graphql:
    http:
      path: /api/fleetservice/graphql
    graphiql:
      enabled: true
      path: /api/fleetservice/graphiql

jwt:
  secret: ${JWT_SECRET_KEY}
