server:
  port: 8090

spring:
  application:
    name: fleet-service
  mongodb:
    uri: "mongodb://localhost:27017/fleet"

  graphql:
    http:
      path: /api/fleetservice/graphql
    graphiql:
      path: /graphiql
      enabled: true

jwt:
  secret: jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4