server:
  port: 8090

spring:
  application:
    name: fleet-service
  data:
    mongodb:
      uri: ${ MONGO_URI }

  graphql:
    http:
      path: /api/fleetservice/graphql
    graphiql:
      enabled: true

jwt:
  secret: jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4